apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: "montco"
      volumeMounts:
        - mountPath: "/pod-10g"
          name: task-pv-storage
