apiVersion: v1
kind: PersistentVolume
metadata:
  name: zoo-log-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/zookeeper/log"
