apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: zookeeper
  template:
    metadata:
      labels:
        run: zookeeper
    spec:
      volumes:
        - name: zoo-pv-storage
          persistentVolumeClaim:
            claimName: zoo-pv-claim
        - name: zoo-log-pv-storage
          persistentVolumeClaim:
            claimName: zoo-log-pv-claim	    
      initContainers:
      - name: zoo-pv-storage
        image: alpine:3
        command:
        - chown
        - -R
        - 1000:1000
        - /var/lib/zookeeper
        volumeMounts:
        - name: zoo-pv-storage
          mountPath: /var/lib/zookeeper/data
        - name: zoo-log-pv-storage
          mountPath: /var/lib/zookeeper/log	  
      containers:
        - name: zookeeper
          image: 'confluentinc/cp-zookeeper:6.0.0'
          imagePullPolicy: IfNotPresent
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1152Mi
          ports:
            - containerPort: 2181
              name: zookeeper
          volumeMounts:
            - mountPath: "/var/lib/zookeeper/data"
              name: zoo-pv-storage
            - mountPath: "/var/lib/zookeeper/log"
              name: zoo-log-pv-storage	      

