apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  annotations:
    pv.beta.kubernetes.io/gid: "65532"
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pod-10g"
